name: bimber
description: Tinder like app for organizing alcohol meetings

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  equatable: ^1.2.1
  flare_flutter: ^2.0.5
  page_transition: ^1.1.7+2
  tinycolor: ^1.0.2
  meta: ^1.1.8
  build_context: ^2.0.2
  flutter_form_builder:
    git:
      url: git://github.com/ryanhz/flutter_form_builder.git
      ref: master
  intl: ^0.16.1
  geolocator: ^5.3.2+2
  cached_network_image: ^2.2.0+1
  provider: ^4.3.2
  sprung: ^2.0.0+12
  flutter_chips_input: ^1.9.4
  flutter_cache_manager: ^1.4.2
  shared_preferences: ^0.5.12
  dotted_border: ^1.0.6
  graphql_flutter: ^4.0.0-beta.1
  dio: ^3.0.10
  flutter_dotenv: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/env/.env_dev
  fonts:
  - family: Baloo
    fonts:
    - asset: fonts/Baloo2-ExtraBold.ttf
      weight: 900


  uses-material-design: true

dependency_overrides:
  flutter_chips_input: ^1.9.0-dev.1
