name: bimber
description: Tinder like app for organizing alcohol meetings

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  equatable: ^1.2.1
  flare_flutter: ^2.0.5
  page_transition: "^1.1.5"
  tinycolor: ^1.0.2
  meta: ^1.1.8
  build_context: ^2.0.2
  flutter_form_builder: ^3.12.0
  intl: ^0.16.1
  geolocator: ^5.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  fonts:
  - family: Baloo
    fonts:
    - asset: fonts/Baloo2-ExtraBold.ttf
      weight: 900


  uses-material-design: true

